apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodejs.service.name }}
spec:
  selector:
    app: my-nodejs-app
  ports:
    - protocol: TCP
      port: {{ .Values.nodejs.service.port }}
      targetPort: 3000
  type: {{ .Values.nodejs.service.type }}
